version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0  # Convenience image with Java
    steps:
      - checkout
      - run: mvn clean test  # Or your build/test command
workflows:
  main:
    jobs:
      - build
