version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:25.0  # Convenience image with Java
    steps:
      - checkout
      - run: ./mvnw clean deploy -Ppackagecloud  # Or your build/test command
workflows:
  main:
    jobs:
      - build
